#!/usr/bin/env python

# Authors: see AUTHORS.md at project root.
# CopyPolicy: released under the terms of the LGPLv2.1, see LICENSE at project root.
# URL: https://github.com/asrob-uc3m/robotDevastation-simulator

# Dependencies:
# - https://github.com/roboticslab-uc3m/openrave-yarp-plugins  (provides OpenraveYarpPluginLoader, YarpOpenraveRobotManager, YarpOpenraveRGBDSensor)
# - https://github.com/asrob-uc3m/robotDevastation-openrave-models  (provides mapping_room.env.xml and models)
# - https://github.com/asrob-uc3m/yarp-devices  (provides RobotServer)

import openravepy
from openravepy import *

try:
    RaveInitialize()

    if not RaveLoadPlugin('OpenraveYarpPluginLoader'):
        raveLogError("Plugin not correctly loaded")

    env=Environment()
    env.SetViewer('qtcoin')
    env.Load('/usr/local/share/robotDevastation-openrave-models/openrave/mapping_room.env.xml')

    OpenraveYarpPluginLoader = RaveCreateModule(env,'OpenraveYarpPluginLoader')

    print OpenraveYarpPluginLoader.SendCommand('open --device RobotServer --subdevice YarpOpenraveRobotManager --robotIndex 0 --physics ode')

    print OpenraveYarpPluginLoader.SendCommand('open --device grabber --subdevice YarpOpenraveGrabber --robotIndex 0 --sensorIndex 1 --name /ecroSim/img:o --forceName /ecroSim/img:o')

    print OpenraveYarpPluginLoader.SendCommand('open --device RobotServer --subdevice YarpOpenraveRobotManager --robotIndex 1 --physics ode')

    print OpenraveYarpPluginLoader.SendCommand('open --device grabber --subdevice YarpOpenraveGrabber --robotIndex 1 --sensorIndex 1 --name /ecroSim2/img:o --forceName /ecroSim2/img:o')

    #-- Models have RGBD sensor, but not used in robotDevastation for now.
    #print OpenraveYarpPluginLoader.SendCommand('open --device RGBDSensorWrapper --subdevice YarpOpenraveRGBDSensor --depthSensorIndex 0 --rgbSensorIndex 1')

    while 1:
        pass

finally:
    RaveDestroy()
